package boxy.core.domain;

/**
 * Represents a published event from a partition.
 *
 * <p>Events are immutable once created. The event ID is globally unique across all
 * partitions and is generated by the database auto_increment.
 *
 * @param id Globally unique event identifier (auto-generated)
 * @param partitionId The partition this event belongs to
 * @param data Raw event payload (typically JSON-encoded)
 */
public record Event(
        long id,
        long partitionId,
        String data) {
}
