CREATE PROCEDURE sp_consumers__deregister(IN p_session_id VARCHAR(36))
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; END;
    START TRANSACTION;
        DELETE FROM sessions WHERE id = p_session_id;
    COMMIT;
END;
