CREATE PROCEDURE sp_consumers__delete(IN p_consumer_id VARCHAR(36))
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; END;
    START TRANSACTION;
        DELETE FROM consumers WHERE id = p_consumer_id;
    COMMIT;
END;